using UnityEngine;

public class VibrationManager : MonoBehaviour
{
    public static VibrationManager Instance { get; private set; }

#if UNITY_ANDROID && !UNITY_EDITOR
    private AndroidJavaClass unityPlayer;
    private AndroidJavaObject currentActivity;
    private AndroidJavaObject vibrator;
#endif

    private void Awake()
    {
        if (Instance != null && Instance != this)
        {
            Destroy(gameObject);
            return;
        }

        Instance = this;
        DontDestroyOnLoad(gameObject);

#if UNITY_ANDROID && !UNITY_EDITOR
        unityPlayer = new AndroidJavaClass("com.unity3d.player.UnityPlayer");
        currentActivity = unityPlayer.GetStatic<AndroidJavaObject>("currentActivity");
        vibrator = currentActivity.Call<AndroidJavaObject>(
            "getSystemService",
            "vibrator");
#endif
    }

    public void Vibrate()
    {
#if UNITY_ANDROID && !UNITY_EDITOR
        vibrator?.Call("vibrate");
#else
        Handheld.Vibrate();
#endif
    }

    public void Vibrate(long milliseconds)
    {
#if UNITY_ANDROID && !UNITY_EDITOR
        vibrator?.Call("vibrate", milliseconds);
#else
        Handheld.Vibrate();
#endif
    }

    public void Vibrate(long[] pattern, int repeat)
    {
#if UNITY_ANDROID && !UNITY_EDITOR
        vibrator?.Call("vibrate", pattern, repeat);
#else
        Handheld.Vibrate();
#endif
    }

    public bool HasVibrator()
    {
#if UNITY_ANDROID && !UNITY_EDITOR
        return vibrator != null;
#else
        return false;
#endif
    }

    public void Cancel()
    {
#if UNITY_ANDROID && !UNITY_EDITOR
        vibrator?.Call("cancel");
#endif
    }
}

// public class VibrationManager : MonoBehaviour
// {
//     private static VibrationManager instance;
//     private static readonly object lockObject = new object();

//     private static AndroidJavaObject vibrator = null;
//     private static AndroidJavaClass vibrationEffectClass = null;
//     private static int sdkVersion = 0;

//     public static VibrationManager Instance
//     {
//         get
//         {
//             lock (lockObject)
//             {
//                 if (instance == null)
//                 {
//                     instance = FindFirstObjectByType<VibrationManager>();
//                     if (instance == null)
//                     {
//                         GameObject singletonObject = new GameObject("VibrationManager_Autogenerated");
//                         instance = singletonObject.AddComponent<VibrationManager>();
//                         DontDestroyOnLoad(singletonObject);
//                     }
//                 }
//                 return instance;
//             }
//         }
//     }

//     void Awake()
//     {
//         if (instance != null && instance != this)
//         {
//             Destroy(gameObject);
//             return;
//         }
//         instance = this;
//         DontDestroyOnLoad(gameObject);

//         #if UNITY_ANDROID && !UNITY_EDITOR
//         InitializeAndroidVibrator();
//         #endif
//     }

//     private void InitializeAndroidVibrator()
//     {
//         try
//         {
//             using (AndroidJavaClass unityPlayer = new AndroidJavaClass("com.unity3d.player.UnityPlayer"))
//             using (AndroidJavaObject currentActivity = unityPlayer.GetStatic<AndroidJavaObject>("currentActivity"))
//             {
//                 vibrator = currentActivity.Call<AndroidJavaObject>("getSystemService", "vibrator");
//             }

//             using (AndroidJavaClass buildVersion = new AndroidJavaClass("android.os.Build$VERSION"))
//             {
//                 sdkVersion = buildVersion.GetStatic<int>("SDK_INT");
//             }

//             if (sdkVersion >= 26)
//             {
//                 vibrationEffectClass = new AndroidJavaClass("android.os.VibrationEffect");
//             }
//         }
//         catch (System.Exception e)
//         {
//             Debug.LogError($"VibrationManager Fehler: {e.Message}");
//         }
//     }

//     public void Vibrate(int amplitude)
//     {
//         int milliseconds = 100;
//         int androidAmplitude = 255;
//         string intensityName = "Unbekannt";

//         switch (amplitude)
//         {
//             case 1:
//                 intensityName = "SCHWACH";
//                 androidAmplitude = 35; 
//                 milliseconds = 25;
//                 break;
//             case 2:
//                 intensityName = "MITTEL";
//                 androidAmplitude = 110;
//                 milliseconds = 65;
//                 break;
//             case 3:
//                 intensityName = "STARK";
//                 androidAmplitude = 255;
//                 milliseconds = 130;
//                 break;
//         }

//         #if UNITY_EDITOR
//         Debug.Log($"<color=#00FFCC><b>[VibrationManager]</b></color> Simulation im Editor:\n" +
//                   $"• Stufe: <b>{intensityName}</b> ({amplitude})\n" +
//                   $"• Dauer: {milliseconds} ms | Amplitude: {androidAmplitude}/255");
//         #elif UNITY_ANDROID
//         if (vibrator == null || !vibrator.Call<bool>("hasVibrator")) return;

//         // UNIVERSAL-ANSATZ FÜR ALLE GERÄTE (Ab Android 8.0 / API 26)
//         // Erzeugt ein Mini-Muster, das UI-Sperren auf Xiaomi umgeht und überall sonst normal läuft
//         if (sdkVersion >= 26 && vibrationEffectClass != null)
//         {
//             long[] timings = new long[] { 0, milliseconds };
//             int[] amplitudes = new int[] { 0, androidAmplitude };
            
//             AndroidJavaObject effect = vibrationEffectClass.CallStatic<AndroidJavaObject>("createWaveform", timings, amplitudes, -1);
//             vibrator.Call("vibrate", effect);
//         }
//         else
//         {
//             // Fallback für uralte Android-Geräte
//             vibrator.Call("vibrate", (long)milliseconds);
//         }
//         #endif
//     }
// }




// using UnityEngine;

// public class VibrationManager : MonoBehaviour
// {
//     private static VibrationManager instance;
//     private static readonly object lockObject = new object();

//     private static AndroidJavaObject vibrator = null;
//     private static AndroidJavaClass vibrationEffectClass = null;
//     private static int sdkVersion = 0;

//     /// <summary>
//     /// Globaler Zugriffspunkt auf das Singleton.
//     /// Erstellt sich bei Bedarf selbst.
//     /// </summary>
//     public static VibrationManager Instance
//     {
//         get
//         {
//             lock (lockObject)
//             {
//                 if (instance == null)
//                 {
//                     instance = FindFirstObjectByType<VibrationManager>();

//                     if (instance == null)
//                     {
//                         GameObject singletonObject = new GameObject("VibrationManager_Autogenerated");
//                         instance = singletonObject.AddComponent<VibrationManager>();
//                         DontDestroyOnLoad(singletonObject);
//                     }
//                 }
//                 return instance;
//             }
//         }
//     }

//     void Awake()
//     {
//         if (instance != null && instance != this)
//         {
//             Destroy(gameObject);
//             return;
//         }

//         instance = this;
//         DontDestroyOnLoad(gameObject);

//         #if UNITY_ANDROID && !UNITY_EDITOR
//         InitializeAndroidVibrator();
//         #endif
//     }

//     private void InitializeAndroidVibrator()
//     {
//         try
//         {
//             using (AndroidJavaClass unityPlayer = new AndroidJavaClass("com.unity3d.player.UnityPlayer"))
//             using (AndroidJavaObject currentActivity = unityPlayer.GetStatic<AndroidJavaObject>("currentActivity"))
//             {
//                 vibrator = currentActivity.Call<AndroidJavaObject>("getSystemService", "vibrator");
//             }

//             using (AndroidJavaClass buildVersion = new AndroidJavaClass("android.os.Build$VERSION"))
//             {
//                 sdkVersion = buildVersion.GetStatic<int>("SDK_INT");
//             }

//             if (sdkVersion >= 26)
//             {
//                 vibrationEffectClass = new AndroidJavaClass("android.os.VibrationEffect");
//             }
//         }
//         catch (System.Exception e)
//         {
//             Debug.LogError($"VibrationManager Fehler bei Android-Initialisierung: {e.Message}");
//         }
//     }

//     /// <summary>
//     /// Löst eine Vibration in drei Stufen aus und loggt Details im Unity Editor.
//     /// </summary>
//     /// <param name="amplitude">Stärke: 1 (schwach), 2 (mittel), 3 (stark)</param>
//     public void Vibrate(int amplitude)
//     {
//         int milliseconds = 100;
//         int androidAmplitude = 255;
//         string intensityName = "Unbekannt";

//         // Berechne die Werte im Voraus, um sie sowohl für Android als auch für den Editor-Log zu nutzen
//         switch (amplitude)
//         {
//             case 1:
//                 intensityName = "SCHWACH";
//                 androidAmplitude = 40; 
//                 milliseconds = 40;
//                 break;
//             case 2:
//                 intensityName = "MITTEL";
//                 androidAmplitude = 120;
//                 milliseconds = 80;
//                 break;
//             case 3:
//                 intensityName = "STARK";
//                 androidAmplitude = 255;
//                 milliseconds = 150;
//                 break;
//         }

//         #if UNITY_EDITOR
//         // Ausführliches Debug-Logging für den Unity Editor
//         Debug.Log($"<color=#00FFCC><b>[VibrationManager]</b></color> Simulation im Editor:\n" +
//                   $"• Stufe: <b>{intensityName}</b> ({amplitude})\n" +
//                   $"• Dauer: {milliseconds} ms\n" +
//                   $"• Android-Amplitude: {androidAmplitude}/255");
//         #elif UNITY_ANDROID
//         if (vibrator == null || !vibrator.Call<bool>("hasVibrator")) return;

//         if (sdkVersion >= 26 && vibrationEffectClass != null)
//         {
//             AndroidJavaObject effect = vibrationEffectClass.CallStatic<AndroidJavaObject>("createOneShot", (long)milliseconds, androidAmplitude);
//             vibrator.Call("vibrate", effect);
//         }
//         else
//         {
//             // Fallback für alte Android-Geräte (< API 26) - Nur zeitgesteuert
//             vibrator.Call("vibrate", (long)milliseconds);
//         }
//         #endif
//     }
// }
